#![feature(min_specialization, auto_traits, negative_impls)]
pub mod config;
pub mod epidemic;
pub mod events;
pub mod models;
pub mod params;
pub mod prelude;
pub mod sampler;
pub mod sim;
pub mod trackers;
pub mod utils;
